openapi: 3.0.0
info:
  title: Application Manufaktur
  description: |-
    Aplikasi Manufaktur Sederhana
  contact:
    email: maulanaferdie1@gmail.com
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Test local computer
tags:
  - name: Suppliers
    description: Daftar API Suppliers
  - name: Products
    description: Daftar API Products
  - name: Components
    description: Daftar API Components
paths:
  /suppliers:
    post:
      tags:
        - Suppliers
      summary: Mendaftarkan Suppliers Baru
      description: API ini adalah untuk Mendaftarkan Suppliers Baru
      operationId: post-create-suppliers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: ferdie
                address:
                  type: string
                  example: pekanbaru
      responses:
        "201":
          description: Success Register
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: succes
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: ferdie
                      address:
                        type: string
                        example: pekanbaru
                      createdAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type: string
                        format: date-time
        "400":
          description: Error from user
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
                  - type: object
                    properties:
                      status:
                        type: boolean
                      message:
                        type: string
              examples:
                duplicated-account:
                  summary: If account already created
                  value:
                    status: false
                    message: supplier is already created!
                bad-request:
                  summary: If required data is not provided
                  value:
                    status: false
                    message: name or email is required!
    get:
      tags:
        - Suppliers
      summary: Mendapatkan semua data suppliers
      description: API ini adalah untuk Mendapatkan semua data suppliers
      operationId: post-getAll-suppliers
      responses:
        "201":
          description: Success Register
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: succes
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: ferdie
                        address:
                          type: string
                          example: pekanbaru
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time
  /suppliers/{id_supplier}:
    get:
      tags:
        - Suppliers
      summary: Mendapatkan semua data suppliers
      description: API ini adalah untuk Mendapatkan semua data suppliers
      operationId: post-getAll-suppliers
      responses:
        "201":
          description: Success Register
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: succes
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        name:
                          type: string
                          example: ferdie
                        address:
                          type: string
                          example: pekanbaru
                        createdAt:
                          type: string
                          format: date-time
                        updatedAt:
                          type: string
                          format: date-time